package modelo;
// Generated 4 mar 2025, 10:26:20 by Hibernate Tools 6.5.1.Final

/**
 * Perfil generated by hbm2java
 */
public class Perfil implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private String clave;
	private byte[] foto;
	private String estado;
	private String tipo;

	public Perfil() {
	}

	public Perfil(String nombre, String clave, String estado) {
		this.nombre = nombre;
		this.clave = clave;
		this.estado = estado;
	}

	public Perfil(String nombre, String clave, byte[] foto, String estado, String tipo) {
		this.nombre = nombre;
		this.clave = clave;
		this.foto = foto;
		this.estado = estado;
		this.tipo = tipo;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getClave() {
		return this.clave;
	}

	public void setClave(String clave) {
		this.clave = clave;
	}

	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
