package modelo;
// Generated 4 mar 2025, 10:26:20 by Hibernate Tools 6.5.1.Final

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private byte[] foto;
	private int cantidad;
	private int limite;
	private String estado;

	public Producto() {
	}

	public Producto(String nombre, int cantidad, int limite, String estado) {
		this.nombre = nombre;
		this.cantidad = cantidad;
		this.limite = limite;
		this.estado = estado;
	}

	public Producto(String nombre, byte[] foto, int cantidad, int limite, String estado) {
		this.nombre = nombre;
		this.foto = foto;
		this.cantidad = cantidad;
		this.limite = limite;
		this.estado = estado;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public byte[] getFoto() {
		return this.foto;
	}

	public void setFoto(byte[] foto) {
		this.foto = foto;
	}

	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	public int getLimite() {
		return this.limite;
	}

	public void setLimite(int limite) {
		this.limite = limite;
	}

	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

}
